version: '3.8'

services:
  usuarios_service:
    build:
      context: ./services/usuarios
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./services/usuarios:/app
    environment:
      - PYTHONPATH=/app

  pedidos_service:
    build:
      context: ./services/pedidos
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./services/pedidos:/app
    environment:
      - PYTHONPATH=/app
