version: '3.8'

services:
  usuarios_service:
    build:
      context: ./services/usuarios
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      # CAMBIO AQUÍ: Montar en la ruta anidada
      - ./services/usuarios:/app/services/usuarios
    environment:
      - PYTHONPATH=/app

  pedidos_service:
    build:
      context: ./services/pedidos
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      # CAMBIO AQUÍ: Montar en la ruta anidada
      - ./services/pedidos:/app/services/pedidos
    environment:
      - PYTHONPATH=/app
